config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update, :show]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    #last_message_id = params[:id]
    @messages = group.messages.includes(:user).where("id > ?", params[:id])
    # if params[:id] == ""
    #   @messages = group.messages
    # else
    #   @messages = group.messages.includes(:user).where("id > ?", params[:id])
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :body)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
    
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%" ).where.not(id:current_user)
    respond_to do |format|
      format.html
      format.json
    end
  end


  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
= form_for(article) do |f|
  - if article.errors.any?
    #error_explanation
      %h2
        = pluralize(article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - article.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :body
    = f.text_field :body
  .actions
    = f.submit

app/views/articles/edit.html.haml
%h1 Editing Article
= render 'form', article: @article
= link_to 'Show', @article
|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%p#notice= notice
%h1 Articles
%table
  %thead
    %tr
      %th Title
      %th Author
      %th Body
      %th{:colspan => "3"}
  %tbody
    - @articles.each do |article|
      %tr
        %td= article.title
        %td= article.author
        %td= article.body
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New Article
= render 'form', article: @article
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @article.title
%p
  %strong Author:
  = @article.author
%p
  %strong Body:
  = @article.body
= link_to 'Edit', edit_article_path(@article)
|
= link_to 'Back', articles_path

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: 'chat-group_チャットメンバーを追加'} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :users, id: 'user-search-field', class: 'chat-group-form__input', value: '', placeholder: '追加したいユーザー名を入力してください'
        #user-search-result



  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー

    .chat-group-form__field--right
      #chat-group-users
        - @group.users.each do |user|
          #chat-group-user-8.chat-group-user.clearfix.js-chat-member{id: current_user.id}
            %input{name: 'group[user_ids][]', type: 'hidden', value: "#{ user.id }"}
            %p.chat-group-user__name
              = user.name

            %p.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 
              - unless current_user.id == user.id
                削除
              
      #member_search_result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatSpace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.haml
.message{"data-message-id": "#{message.id}"}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = message.created_at.strftime("%Y年 %m月 %d日 %H:%M")
  .lower-message
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper

  = render 'shared/side_bar'

  .chat
    .header
      .left-header
        .left-header__title
          = @group.name
        %ul.left-header__members
          メンバー：
          %li.heder__left__members_member

            - @group.group_users.each do |group_user|
              = group_user.user.name

      .right-header
        .right-header__button
        =link_to edit_group_path(@group.id),class:'right-header__button' do
          Edit

    .messages
      = render @messages
        
    .form
      = form_for [@group, @message] do |f|
        = f.text_field :content, class: 'form__message', placeholder: 'type a message'
        .form__mask
          = f.label :image, class: 'form__mask__image' do
            = fa_icon 'picture-o', class: 'icon'
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'